### PR TITLE
Compatibility with Redmine 5

### PR DESCRIPTION
**Pull request by dosyfier**
This PR provides the necessary adaptations to make gitolite-rugged gem compatible with Redmine 5, which include:
* Upgrading rugged from ~1.1 to ~1.5, for Ruby 3.x compatibility purposes
* Moving files depending on the faker gem from lib/ to spec/

### CODE REVIEW

**Comment by PowerKiKi** [comment]
@n-rodriguez could you please take care of this PR, or alternatively add myself and @alexandermeindl to this repository so we can help get redmine_git_hosting compatible with Redmine 5 (via https://github.com/jbox-web/redmine_git_hosting/pull/815)

**Comment by prahal** [comment]
@dosyfier you might want to set the rugged version to the lowest possible ie 1.2.0 (as you told it was the first version that shipped the required fix for ruby 3).
Debian for one does not ship ruby-rugged above 1.2.0.
I could locally build a 1.5.0 version with gem2deb but that seems unnecessary.

**Comment by n-rodriguez** [comment]
> alternatively add myself and @alexandermeindl to this repository so we can help get redmine_git_hosting compatible with Redmine 5

@PowerKiKi done! thank you!

**Comment by PowerKiKi** [comment]
@n-rodriguez thank you for adding me. Could you please configure the missing [`CC_TEST_REPORTER_ID`](https://docs.codeclimate.com/docs/finding-your-test-coverage-token) so that CI will pass ? or alternatively add myself to [Code Climate](https://codeclimate.com/) as an owner so I can do it myself ?

Failing that I will remove all integrations with Code Climate, so that the CI can pass, but I suppose it would be better to keep Code Climate if possible.

**Comment by PowerKiKi** [comment]
@prahal my understanding is that `rugged` is a ruby gem and as such you should use `bundler` to install it, instead of depending on debian provided `ruby-rugged` package. This should solve issues about obsolete versions.

Also the [`--with-ssh` is only available since 1.5.0](https://github.com/libgit2/rugged/commit/7ef9ce7983131906302cde5c32b068976b312b9b). And it is something that will be used very soon by redmine_git_hosting: https://github.com/jbox-web/redmine_git_hosting/pull/813/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R132

**Comment by prahal** [comment]
@PowerKiKi  fair with me about depending on rugged 1.5.0 when redmine_git_plugin, as I believe there will be no release or tag between the current code and this commit that requires it.

Still, there are good rationales for keeping dependency to the lowest possible when possible (and I even prefer a range with a max version that should match the next major version and could be increased when the next major version is released and is known to work and a min version that matches what is required for the current code to work).

Also, I prefer Debian packaged gem when possible. I use the Debian Redmine package, but it runs bundler as root (with --local). I could run bundler as root too to download and build the gems but I prefer not to (even if admit I do at times). Also with non-Debian packaged gems, I tend to have very hard-to-debug bundler errors and already lost countless hours. Having a Debian package for redmine_git_hosting and its dependencies would be a time saver (quite easy with gem2deb, except for redmine_git_hosting dependencies on custom gitlab-grack - what about releasing a jboxweb-grack gem ? -, and to a lesser extent on this non-released git repository).

**Comment by n-rodriguez** [comment]
> Could you please configure the missing [`CC_TEST_REPORTER_ID`](https://docs.codeclimate.com/docs/finding-your-test-coverage-token) so that CI will pass ? or alternatively add myself to [Code Climate](https://codeclimate.com/) as an owner so I can do it myself ?

Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

**Comment by PowerKiKi** [comment]
Code climate [docs](https://docs.codeclimate.com/docs/finding-your-test-coverage-token) days that it is not sensitive and it should not be considered a secret. Do you agree to write it in clear text ?

**Comment by n-rodriguez** [comment]
ok :+1:

**Comment by PowerKiKi** [comment]
So can you please share the value here ? Or add it yourself to the CI please?

**Comment by n-rodriguez** [comment]
3dfc7b128d751fb7905e3fc1b919d81b9203ef295341ea324305fac22a8be8bc

**Pull request merged**
